<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <link name="base_link"></link>

    <joint name="chassis_joint" type="fixed">
        <origin xyz="0 0 0.225" />
        <parent link="base_link" />
        <child link="chassis" />
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 0.1" />
            <geometry>
                <box size="1.0 0.65 0.2" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0 0 0.1" />
            <geometry>
                <box size="1.0 0.65 0.2" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="40" x="1.0" y="0.65" z="0.25">
            <origin xyz="0 0 0.1" />
        </xacro:inertial_box>
    </link>


    
    <!-- FRONT LEFT WHEEL -->

    <joint name="fl_rotation_joint" type="fixed">
        <origin xyz="0.45 0.3 ${wheel_radius}" rpy="0 0 0"/>
        <parent link="base_link" />
        <child link="fl_axle_link" />
        <axis xyz="0 0 1" />
        <!-- <limit
            upper="${pi/2}"
            lower="-${pi/2}"
            effort="1000"
            velocity="1000" />
        <dynamics
            damping="0.2"
            friction="0.2" /> -->
    </joint>

    <link name="fl_axle_link">
        <visual>
            <origin xyz="0 0 ${axle_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${axle_radius}" length="${axle_length}"/>
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 ${axle_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${axle_radius}" length="${axle_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${axle_mass}" length="${axle_length}" radius="${axle_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>


    <joint name="fl_wheel_joint" type="continuous">
        <origin xyz="0 0 0" rpy="-${pi/2} 0 0"/>
        <parent link="fl_axle_link" />
        <child link="fl_wheel" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="fl_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>



<!-- FRONT RIGHT WHEEL -->

    <joint name="fr_rotation_joint" type="fixed">
        <origin xyz="0.45 -0.3 ${wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="fr_axle_link" />
        <axis xyz="0 0 1" />
        <!-- <limit
            upper="${pi/2}"
            lower="-${pi/2}"
            effort="1000"
            velocity="1000" />
        <dynamics
            damping="0.2"
            friction="0.2" /> -->
    </joint>

    <link name="fr_axle_link">
        <visual>
            <origin xyz="0 0 ${axle_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${axle_radius}" length="${axle_length}"/>
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 ${axle_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${axle_radius}" length="${axle_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${axle_mass}" length="${axle_length}" radius="${axle_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>


    <joint name="fr_wheel_joint" type="continuous">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <parent link="fr_axle_link" />
        <child link="fr_wheel" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="fr_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>



    <!-- REAR LEFT WHEEL -->

    <joint name="rl_rotation_joint" type="fixed">
        <origin xyz="-0.45 0.3 ${wheel_radius}" rpy="0 0 0"/>
        <parent link="base_link" />
        <child link="rl_axle_link" />
        <axis xyz="0 0 1" />
        <!-- <limit
            upper="${pi/2}"
            lower="-${pi/2}"
            effort="1000"
            velocity="1000" />
        <dynamics
            damping="0.2"
            friction="0.2" /> -->
    </joint>

    <link name="rl_axle_link">
        <visual>
            <origin xyz="0 0 ${axle_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${axle_radius}" length="${axle_length}"/>
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 ${axle_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${axle_radius}" length="${axle_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${axle_mass}" length="${axle_length}" radius="${axle_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>


    <joint name="rl_wheel_joint" type="continuous">
        <origin xyz="0 0 0" rpy="-${pi/2} 0 0"/>
        <parent link="rl_axle_link" />
        <child link="rl_wheel" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="rl_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>



    <!-- REAR RIGHT WHEEL -->

    <joint name="rr_rotation_joint" type="fixed">
        <origin xyz="-0.45 -0.3 ${wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="rr_axle_link" />
        <axis xyz="0 0 1" />
        <!-- <limit
            upper="${pi/2}"
            lower="-${pi/2}"
            effort="1000"
            velocity="1000" />
        <dynamics
            damping="0.2"
            friction="0.2" /> -->
    </joint>

    <link name="rr_axle_link">
        <visual>
            <origin xyz="0 0 ${axle_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${axle_radius}" length="${axle_length}"/>
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="0 0 ${axle_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${axle_radius}" length="${axle_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${axle_mass}" length="${axle_length}" radius="${axle_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <joint name="rr_wheel_joint" type="continuous">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <parent link="rr_axle_link" />
        <child link="rr_wheel" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="rr_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

</robot>